# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  major: '1'
  minor: '0'
  revision: $[counter(variables['minor'], 1)] # This will get reset every time minor gets bumped.
  nugetVersion: '$(major).$(minor).$(revision)'


steps:
- task: UseDotNet@2
  inputs:
    version: '6.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'ClassLibraryProjects.sln'  # Change this to your solution file

- task: VSBuild@1
  inputs:
    solution: 'ClassLibraryProjects.sln'  # Change this to your solution file
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'StringLibrary/StringLibrary.csproj'
    packDirectory: '$(build.artifactStagingDirectory)/nuget'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'nugetVersion'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)/nuget'
    ArtifactName: 'nuget'

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true

- task: NuGetCommand@2
  inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'Lab4'
      allowPackageConflicts: true
  displayName: 'Push NuGet Package'
